### ISSUE TITLE
Not redirecting to offline on first page load

### ISSUE THREAD

**Issue by arifje** [selvinortiz/craft-plugin-patrol#10]
When maintenance mode is enabled it doesn't redirect on first page load, but only after a refresh.

Steps to reproduce;

- enable maintenance mode
- open a new tab in browser
- fill in the URL of the website and press enter
- page loads
- F5 the page, it redirects to /offline

**Comment by selvinortiz** [comment]
That seems odd.

I'll try to take a look at it this week.

**Comment by selvinortiz** [comment]
@skoften I was not able to reproduce this issue.

Did you experience this on a fresh install of Patrol 3 without any custom configuration other than enabling maintenance mode?

**Comment by selvinortiz** [comment]
@skoften I received a similar report and in that instance, it turned out to be an issue with their local env dev.
