### ISSUE TITLE
Feature: Ability to add notes against each whitelisted ip address

### ISSUE THREAD

**Issue by sergeifilippov** [selvinortiz/craft-plugin-patrol#15]
This will allow you to make a note who the ip address is for so that 6 months you can remember the context of the whitelisted ips.

<img width="894" alt="patrol - plugins - barrington 2018-11-13 22-49-55" src="https://user-images.githubusercontent.com/123676/48405084-8064cb00-e796-11e8-94eb-f5d3ec6daff0.png">

**Comment by selvinortiz** [comment]
@sergeifilippov Working on this for the next release.

**Comment by engram-design** [comment]
I've actually simplified the management of these IPs to just be a `<textarea>`. As such, you can now just add comments, either inline, or as a new line:

```
::1 # Office IPs

# Office IPs
127.0.0.1
```
