### ISSUE TITLE
maintenanceModeAccessTokens doesn't work

### ISSUE THREAD

**Issue by jesuismaxime** [selvinortiz/craft-plugin-patrol#19]
I had add `maintenanceModeAccessTokens` on my config file (and remove properly the `maintenanceModeAuthorizedIps` param and I'm not able to make it work.

When I hit my site.com/​?​a​c​c​e​s​s​=​my-token I see the 404 page, when I try to acces another page I'm redirect to the `maintenanceModePageUrl` page and the IP is not added at the whitelist (I guess the CP "Authorized IPs" section display the actual whitelist).

Here's my `patrol.php` (note the issue is for the `staging` env)

```
<?php

return [
	'*' => [

		// SSL
		'sslRoutingEnabled' => true,
		'sslRoutingRestrictedUrls' => ['/'],
		'sslRoutingBaseUrl' => "https://example.ca",
		//
		'maintenanceModePageUrl' => '/nada-que-ver',
	],
	'dev' => [
		'maintenanceModeEnabled' => false,
		'sslRoutingEnabled' => false,
		'maintenanceModeAuthorizedIps' => [],
	],
	'staging' => [
		'maintenanceModeEnabled' => true,
		'maintenanceModeAccessTokens' => [
			'd0nn3bd8a2iza1ikjxxdo28iicabh7ts',
			'test',
		],
	],
	'production' => [
	]
];

```

**Comment by selvinortiz** [comment]
@jesuismaxime Can you remove the `maintenanceModeAuthorizedIps` config from all the environments and let me know if that solves the issue?

**Comment by jesuismaxime** [comment]
Sorry for the delay, did'nt work on that project  since today! Yes, that "solves" the issue, but not working as expected.

**Comment by selvinortiz** [comment]
@jesuismaxime Can you clarify how you expect it to work and how it's not working that way?

**Comment by jesuismaxime** [comment]
I expected the env params to work like others in Craft configs: by environment. The way it works now, I cant have a staging environment with `maintenanceModeAuthorizedIps` and a production environment with `maintenanceModeAccessTokens`.

And It could be nice to use both `maintenanceModeAuthorizedIps` and `maintenanceModeAccessTokens` on a environment.

**Comment by selvinortiz** [comment]
Got it!

Yes, I agree that it would be nice.

I'll take a look at the level of effort required to make that happen.

However, it won't be something I'll address in the near future.
