### ISSUE TITLE
Not forcing HTTPS

### ISSUE THREAD

**Issue by mikefrancis** [selvinortiz/craft-plugin-patrol#2]
Hi,

I installed this plugin and ticked the "Enable SSL routing and force HTTPS using the rules defined below" switch, yet when I go to my site via `http://` I don't get redirected?

**Comment by selvinortiz** [comment]
@mikefrancis This version of the plugin for Craft 3 is in early development, but I'll take a look and see if I can find a reason why this may be happening. Could be a beta update in Craft 3 that broke something, since I haven't had a chance to work on the plugin since beta 10 I think.

**Comment by mikefrancis** [comment]
@selvinortiz Strangely this seems to work locally but not on my site in production, hosted on Heroku.

🤔

**Comment by selvinortiz** [comment]
@mikefrancis Are you using multi-env config that could be causing Patrol to be enabled locally but not on production?

**Comment by mikefrancis** [comment]
@selvinortiz It's been a while since I looked at this but pretty sure I just had it permanently turned on, but it still didn't work.

In the end I just used the nginx config to redirect any non-https traffic to https.
