### ISSUE TITLE
Force SSL only works when ticked in CP.

### ISSUE THREAD

**Issue by brandondeweese** [selvinortiz/craft-plugin-patrol#22]
So I've configured the file config to force SSL on my sites. HTTPS works fine, but HTTP doesn't redirect even though 'sslRoutingEnabled' => true. It doesn't look like this is supposed to happen, right? Heres my config:

`
return [
    // Global settings
    '*' => [
      'primaryDomain' => null,

      'sslRoutingRestrictedUrls' => ['/'],

      // Default Week Start Day (0 = Sunday, 1 = Monday...)
      'defaultWeekStartDay' => 1,

      // Whether generated URLs should omit "index.php"
      'omitScriptNameInUrls' => true,

      // Control Panel trigger word
      'cpTrigger' => 'admin',

      // The secure key Craft will use for hashing and encrypting data
      'securityKey' => getenv('SECURITY_KEY'),

      // Whether to save the project config out to config/project.yaml
      // (see https://docs.craftcms.com/v3/project-config.html)
      'useProjectConfigFile' => false,
  ],

    // Dev environment settings
    'dev' => [
        'allowAdminChanges' => true,
        'devMode' => true,
        'siteUrl' => 'http://etesian.build',
        'sslRoutingEnabled' => false,
    ],

    // Staging environment settings
    'staging' => [
        'allowAdminChanges' => true,
        'devMode' => true,
        'siteUrl' => 'http://etesian.madebyiris.co',
        'sslRoutingEnabled' => false,
    ],

    // Production environment settings
    'production' => [

        'devMode' => false,
        'redirectStatusCode' => 301,
        'sslRoutingEnabled' => true,
        'allowAdminChanges' => true,
        'siteUrl' => 'https://www.etesianwa.com',
        'sslRoutingBaseUrl' => 'https://www.etesianwa.com'
        ],
];
`

**Comment by selvinortiz** [comment]
Hi @brandondeweese,
I apologize for the late reply.

Did you manage to sort this out via Patrol or did you have to do it through NginX/Apache/etc config?

**Comment by engram-design** [comment]
Closing due to age, but that config looks correct!
