### ISSUE TITLE
getRequestingIp() return value bug

### ISSUE THREAD

**Issue by samhibberd** [selvinortiz/craft-plugin-patrol#23]
Hey @selvinortiz 

Ran into an issue with the `getRequestingIp()` method returning a bool value rather than the ip address, just needs the `isset()` removed from the value returned, see:

https://github.com/selvinortiz/craft-plugin-patrol/blob/f6037183324d6046e4121a9005702b39ff89e6b8/src/services/PatrolService.php#L305

https://github.com/selvinortiz/craft-plugin-patrol/blob/f6037183324d6046e4121a9005702b39ff89e6b8/src/services/PatrolService.php#L309

**Comment by engram-design** [comment]
Fixed in [4.0.1](https://github.com/verbb/patrol/releases/tag/4.0.1)
