### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by nickcobley** [selvinortiz/craft-plugin-patrol#27]
Are there any plans to add support for Craft 4?

**Comment by jesuismaxime** [comment]
@selvindev would be great! We already have projects in development using Craft CMS 4 and Patrol was part of our starter kit to control access on both staging and production env.

**Comment by engram-design** [comment]
Added in [5.0.0](https://github.com/verbb/patrol/releases/tag/5.0.0)
