### ISSUE TITLE
Feature Request: Client Access Code

### ISSUE THREAD

**Issue by samhibberd** [selvinortiz/craft-plugin-patrol#6]
Hi @selvinortiz, 

Invaluable plugin!

We found the client access link feature of the Craft 2 plugin IP Whitelist plugin really really useful.

It allowed us to send a unique link to a client which would automatically and their IP address to the allowed list. So rather than requiring (for each new location) to ask the client to google for their IP, add it to config, prepare a release, release let client know, you just send something like this:

`https://staging.site.com?access=75hnf75hi38yryu588uh3jyy5huy678h3`

Be great to see something like this in the already awesome Patrol!

**Comment by selvinortiz** [comment]
@samhibberd I'm working on an update to the plugin and this feature request sounds like a great idea. I'll explore how I can bring this into the plugin.

**Comment by selvinortiz** [comment]
@samhibberd This was added in the today's release https://github.com/selvinortiz/craft-plugin-patrol/releases/tag/3.1.0

**Comment by samhibberd** [comment]
Awesome. Nice one @selvinortiz

**Comment by samhibberd** [comment]
@selvinortiz this is working great! Just a quick follow up, it would be really useful if you could include the token link in the cp somewhere?

**Comment by selvinortiz** [comment]
@samhibberd Where do you think it would be the best place for it? In the CP sidebar, or settings screen maybe? Patrol supports multiple tokens, so we would have to support multiple links.

**Comment by samhibberd** [comment]
@selvinortiz in the settings screen would be fine, but a separate section for access tokens might be cool as you could introduce a permission such that uses could access / share tokens but not the plugin settings. Just thinking out loud :)
