### ISSUE TITLE
primaryDomain doesn't seem to be working

### ISSUE THREAD

**Issue by marcushouse** [selvinortiz/craft-plugin-patrol#7]
Using fresh install of Craft 3 (installed from within Craft3 Plugin browser) sslRoutingEnabled working fine but the primaryDomain setting I have here sitting beside it doesn't seem to do anything. I can't actually see anything in the code for primaryDomain that seems to be doing anything (only really the declaration in the SettingsModel.php)

Am I doing something silly?

**Comment by selvinortiz** [comment]
@marcushouse I wonder if it's an issue with the Plugin Store not installing the latest version correctly.

It should be version 3.1.0 but in a couple of cases, I've seen the plugin store still using 3.0.2.

If this is the case for you, I can submit an update and see if that triggers the plugin store to use the latest.

**Comment by marcushouse** [comment]
That is exactly what it is. I have here version 3.0.2 only just installed. When I totally remove and try to reinstall it is showing me 3.0.2 still. Tried manually upping composer requirement but it doesn't help it find any updates... weird.

Obviously, I can download the zip manually and install but assume the intention is to have it showing 3.1.0 on the plugin store as well.

Other little thing I just spotted.  Your changelog MD file shows dates for 2019 instead of 2018.

**Comment by selvinortiz** [comment]
@marcushouse I reached out to P&T to see if there is anything in the queue preventing the update. It should get sorted out soon.

**Comment by selvinortiz** [comment]
@marcushouse I just heard from Brandon, it should be good to go now.

**Comment by marcushouse** [comment]
Great. Thanks for that! As soon as I installed the update to 3.1.1 I got redirected away to my primaryDomain. Nice work mate and thanks for the useful plugin.

**Comment by selvinortiz** [comment]
Awesome 👍
